(function($){$(document).ready(function(){var body=$(document.body);var fpGrid=$('.featured-posts .grid-thumb');var drawerOpenToggle=$('.drawer-open-toggle');var drawerMenuToggle=$('.drawer-menu-toggle');var drawerMenuExplore=$('.drawer-menu-explore');var drawerExplore=$('.drawer-explore');var drawerOpenDrawer=$('.drawer-open .drawer');function equalHeight(){$('.grid-thumb').matchHeight();}
equalHeight();function fitVids(){$('.post iframe').not('.fitvid iframe').wrap('<div class="fitvid"/>');$('.fitvid').fitVids();}
fitVids();$('.comments-toggle').click(function(e){$('#comments,#disqus_thread').fadeToggle(400);$('.comments-toggle span').toggle();return false;});if(document.location.href.indexOf('#comment')>-1){$('#comments').show();$('.comments-toggle span').toggle();var commentID=window.location.hash.substr(1);$('html,body').animate({scrollTop:$('#'+commentID).offset().top-25},600);}
drawerOpenToggle.click(function(e){drawerMenuExplore.removeClass('show-drawer');drawerMenuToggle.removeClass('drawer-toggle-switch');drawerExplore.toggleClass('show-drawer');body.toggleClass('drawer-open');$(this).toggleClass('drawer-toggle-switch');return false;});drawerMenuToggle.click(function(e){drawerExplore.removeClass('show-drawer');drawerOpenToggle.removeClass('drawer-toggle-switch');drawerMenuExplore.toggleClass('show-drawer');body.toggleClass('drawer-open');drawerMenuToggle.toggleClass('drawer-toggle-switch');return false;});$('html').click(function(){drawerOpenDrawer.slideUp(200);$('body.drawer-open').removeClass('drawer-open');$('.drawer').removeClass('show-drawer');$('.drawer-toggle').removeClass('drawer-toggle-switch');});$(document).keyup(function(e){if(e.keyCode==27){drawerOpenDrawer.slideUp(200);$('body.drawer-open').removeClass('drawer-open');$('.drawer-toggle').removeClass('drawer-toggle-switch');$('.drawer').removeClass('show-drawer');$('.featured-posts .grid-thumb').removeClass('fadeInUp').hide();$('.featured-posts').removeClass('show');$('#site-navigation .current-menu-item').removeClass('current-menu-item');$('.current-menu-item-original').addClass('current-menu-item');}});$('.drawer').click(function(event){event.stopPropagation();});$('.mini-bar .drawer-open-toggle').click(function(e){$('html,body').animate({scrollTop:0},400);$('.drawer-open-toggle').toggleClass('drawer-toggle-switch');return false;});if((paperback_js_vars.load_fixed)=='true'){$('.mini-bar').headroom({offset:200,tolerance:10});}
$('.back-to-top a').click(function(e){e.preventDefault();$('html,body').animate({scrollTop:0},700);return false;});$('.back-to-menu a').click(function(e){e.preventDefault();$('html,body').animate({scrollTop:0},700);$('.drawer-menu-toggle').trigger('click');return false;});var $slides=$('.hero-posts');$slides.responsiveSlides({auto:false,speed:200,nav:true,navContainer:".pager-navs",manualControls:'#hero-pager'});$('.home .hero-wrapper .rslides').each(function(){$(this).swipe({swipeLeft:function(){$(this).parent().find('.rslides_nav.prev').click();},swipeRight:function(){$(this).parent().find('.rslides_nav.next').click();}});});$('.entry-content img').each(function(){$(this).parent().addClass('no-underline');});$('.main-navigation .children').addClass('sub-menu');$('.main-navigation .page_item_has_children').addClass('menu-item-has-children');$(window).on("resize load",function(){var current_width=$(window).width();var post_navs=$('.single .post-navigation');if(current_width>1024){drawerOpenToggle.click(function(e){$('#big-search').focus();return false;});}
if(current_width<769){$(post_navs).insertAfter('#comments');}
else{$('.site-identity .toggle-sub').remove();$(post_navs).insertAfter('#page');equalHeight();}});var item=$('<button class="toggle-sub" aria-expanded="false"><i class="fa fa-plus-square"></i></button>');if($('.drawer .menu-item-has-children .toggle-sub').length==0){$('.drawer .menu-item-has-children,.drawer .page_item_has_children').append(item);}
$('.drawer .menu-item-has-children .toggle-sub').click(function(e){$(this).each(function(){e.preventDefault();$(this).attr('aria-expanded',($(this).attr('aria-expanded')=='false')?'true':'false');$(this).closest('.menu-item-has-children').toggleClass('drop-open');$(this).prev('.sub-menu').toggleClass('drop-active');$(this).find('i').toggleClass('fa-plus-square').toggleClass('fa-minus-square');});});var megaNavLink=$('#site-navigation a');megaNavLink.click(function(event){var catLink=$(this).attr('data-object-id');if(typeof catLink!==typeof undefined&&catLink!==false){event.preventDefault();var id=$(this).attr('data-object-id');var container=$('.post-container');var catHeader=$('.featured-header-category');var data={action:'paperback_category',id:id}
$.ajax({data:data,type:"POST",dataType:"json",url:paperback_js_vars.ajaxurl,success:function(response){container.html(response.html);catHeader.html(response.term_html);$('.post-container').removeClass('post-loading');$('.featured-posts').removeClass('hide');if($('.show .post-container').is(':empty')){$('.featured-posts').addClass('hide');}
fade_images();},error:function(response){container.html(response.html);}});$(this).parent().siblings().removeClass('current-menu-item');$(this).parent().addClass('current-menu-item');$('.sub-menu').addClass('hide-sub');$('.featured-posts').addClass('show');container.show();}});$('.menu-item-has-children').on('mouseover',function(){$('.sub-menu').removeClass('hide-sub');});$('.featured-header-close').click(function(e){$('.featured-posts .grid-thumb').removeClass('fadeInUp').hide();$('.featured-posts').removeClass('show');$('#site-navigation .current-menu-item').removeClass('current-menu-item');$('.current-menu-item-original').addClass('current-menu-item');return false;});$(document.body).on("post-load",function(){var $container=$('.grid-wrapper');var $newItems=$('.new-infinite-posts').not('.is--replaced');var $elements=$newItems.find('.post');$('.new-infinite-posts,.infinite-loader').remove();$container.append($elements);fitVids();});});})(jQuery);jQuery(document).ready(function($){$().navmain();});(function($){jQuery.fn.navmain=function(options){var settings={indicator:false,speed:100,hideClickOut:true}
$.extend(settings,options);var menu=$(".navmain");var lastScreenWidth=window.innerWidth;if(settings.indicator==true){$(menu).find("a").each(function(){if($(this).siblings(".dropdown").length>0){$(this).append();}});}
$(menu).prepend();screenSize();$(window).resize(function(){if(lastScreenWidth<=0&&window.innerWidth>0){unbindEvents();hideCollapse();bindHover();}
if(lastScreenWidth>0&&window.innerWidth<=0){unbindEvents();showCollapse();bindClick();}
lastScreenWidth=window.innerWidth;});function screenSize(){if(window.innerWidth<=0){showCollapse();bindClick();}
else{hideCollapse();bindHover();}}
function bindHover(){if(navigator.userAgent.match(/Mobi/i)||window.navigator.msMaxTouchPoints>0){$(menu).find("a").on("click touchstart",function(e){e.stopPropagation();e.preventDefault();window.location.href=$(this).attr("href");$(this).parent("li").siblings("li").find(".dropdown, .megamenu").stop(true,true).fadeOut(settings.speed);if($(this).siblings(".dropdown, .megamenu").css("display")=="none"){$(this).siblings(".dropdown, .megamenu").stop(true,true).fadeIn(settings.speed);}
else{$(this).siblings(".dropdown, .megamenu").stop(true,true).fadeOut(settings.speed);$(this).siblings(".dropdown").find(".dropdown").stop(true,true).fadeOut(settings.speed);}});if(settings.hideClickOut==true){$(document).bind("click.menu touchstart.menu",function(ev){if($(ev.target).closest(menu).length==0){$(menu).find(".dropdown, .megamenu").fadeOut(settings.speed);}});}}
else{$(menu).find("li").bind("mouseenter",function(){$(this).children(".dropdown, .megamenu").stop(true,true).fadeIn(settings.speed);}).bind("mouseleave",function(){$(this).children(".dropdown, .megamenu").stop(true,true).fadeOut(settings.speed);});}}
function bindClick(){$(menu).find("li:not(.showhide)").each(function(){if($(this).children(".dropdown, .megamenu").length>0){$(this).children("a").bind("click",function(){if($(this).siblings(".dropdown, .megamenu").hasClass("menu-visible")){$(this).siblings(".dropdown, .megamenu").slideUp(settings.speed);$(this).siblings(".dropdown, .megamenu").removeClass("menu-visible");}
else{$(this).siblings(".dropdown, .megamenu").slideDown(settings.speed);$(this).siblings(".dropdown, .megamenu").addClass("menu-visible");firstItemClick=1;}});}});}
function showCollapse(){$(menu).children("li:not(.showhide)").hide(0);$(menu).children("li.showhide").show(0);$(menu).children("li.showhide").bind("click",function(){if($(menu).children("li").is(":hidden")){$(menu).children("li").slideDown(settings.speed);}
else{$(menu).children("li:not(.showhide)").slideUp(settings.speed);$(menu).children("li.showhide").show(0);}});}
function hideCollapse(){$(menu).children("li").show(0);$(menu).children("li.showhide").hide(0);}
function unbindEvents(){$(menu).find("li, a").unbind();$(document).unbind("click.menu touchstart.menu");$(menu).find(".dropdown, .megamenu").hide(0);}}}(jQuery));jQuery(document).ready(function($){"use strict";var str=location.href.toLowerCase();$(".tabs-top li a").each(function(){if(str.indexOf(this.href.toLowerCase())>-1){$("li.highlight").removeClass("highlight");$(this).parent().addClass("highlight");}});jQuery(document).ready(function($){$(".tab_content").hide();$("ul.tabs li:first").addClass("active").show();$(".tab_content:first").show();$("ul.tabs li").click(function(){$("ul.tabs li").removeClass("active");$(this).addClass("active");$(".tab_content").hide();var activeTab=$(this).find("a").attr("href");if($.browser.msie){$(activeTab).show();}
else{$(activeTab).fadeIn();}
return false;});});});